### ISSUE TITLE
Layout Bug

### ISSUE THREAD

**Issue by dontobi** [ThirtyDegreesRay/OpenHub#211]
The layout at the top of the app is not optimal. see the screenshot.

![screenshot_20181225-115753](https://user-images.githubusercontent.com/19261667/50421245-6e6a5380-083d-11e9-8bf3-cf4911f0cece.jpg)

**Comment by MohamedElidrissi** [comment]
Hello, I'm trying to fix this issue but I can't reproduce this, can you tell me your device name ?

**Comment by ZsgsDesign** [comment]
> Hello, I'm trying to fix this issue but I can't reproduce this, can you tell me your device name ?

Samsung S10+ has the same issue

**Comment by MohamedElidrissi** [comment]
I found the problem, it only happens on devices with a notch as mentioned in [#162](https://github.com/ThirtyDegreesRay/OpenHub/issues/162) I will try to fix it even though I don't have a physical phone with a notch

**Comment by MohamedElidrissi** [comment]
Fixed! [pull request](https://github.com/ThirtyDegreesRay/OpenHub/pull/266/commits) pending to be merged :)

**Comment by dontobi** [comment]
@MohamedElidrissi Thanks. I hope the dev will release an update shortly.

**Comment by dontobi** [comment]
The bug still exists. Would it be possible to implement the fix mentioned here?

**Comment by MohamedElidrissi** [comment]
@dontobi well, as you can see, the owner is no longer active on his account so the PR will never be merged.
